"""Tests for schedule trace tables."""

from __future__ import annotations

import sys
from pathlib import Path

import pytest
from export_schedule_trace import (
    detail_of,
    initial_queues,
    main,
    parse_launch_window,
    render_table,
    size_of,
    steady_state_window,
)

from looped_cdb.continuous_depth_batching.schedule_trace import QueueSnapshot, ScheduleTrace, TraceEvent


def _trace() -> ScheduleTrace:
    trace = ScheduleTrace()
    trace.tick = 1
    trace.record("prefill", 2, QueueSnapshot(1, 0, 0, 2, 0, 2), tokens=7)
    trace.record("prelude", 2, QueueSnapshot(1, 2, 0, 2, 0, 2), site="after_prefill_eager")
    trace.tick = 2
    trace.record("recurrent", 3, QueueSnapshot(0, 2, 1, 3, 0, 3), depths={0: 2, 1: 1}, exited=1)
    trace.tick = 3
    trace.record("coda", 1, QueueSnapshot(0, 2, 0, 3, 1, 3))
    return trace


def test_detail_column_shows_one_based_depth_mix_exits_site_and_prompt_tokens() -> None:
    prefill, prelude, recurrent, coda = _trace().events
    assert detail_of(recurrent) == r"$\mathrm{r}_{1}{:}2$ $\mathrm{r}_{2}{:}1$; 1 exit"
    assert detail_of(prelude) == "after prefill"
    assert detail_of(prefill) == "7 prompt tokens"
    assert detail_of(coda) == ""
    assert detail_of(coda, coda_threshold=1) == r"$\lvert Q_C\rvert\ge 1$"
    assert detail_of(coda, coda_threshold=2) == ""
    assert size_of(recurrent) == r"\tracebatch{3}"
    assert size_of(coda) == "1"


def test_render_table_keeps_only_the_window_and_is_a_complete_tabular(tmp_path: Path) -> None:
    trace = _trace()
    path = tmp_path / "trace.jsonl"
    trace.write_jsonl(path)

    table = render_table(ScheduleTrace.load_jsonl(path), source=path, first=2, last=3)

    lines = table.splitlines()
    assert lines[0].startswith("% Generated by scripts/export_schedule_trace.py")
    assert lines[1] == r"\begin{tabular}{rlr>{\raggedright\arraybackslash}p{84pt}rrr}"
    assert lines[-1] == r"\end{tabular}"
    rows = [line for line in lines if line.strip().endswith(r"\\") and not line.strip().startswith("&")]
    assert rows == [
        r"  2 & prelude & 2 & after prefill & 2 & 0 & 1 \\",
        r"  3 & loop & \tracebatch{3} & $\mathrm{r}_{1}{:}2$ $\mathrm{r}_{2}{:}1$; 1 exit & 2 & 1 & 0 \\",
    ]


def test_render_table_can_add_a_title_spanning_all_columns(tmp_path: Path) -> None:
    trace = _trace()
    path = tmp_path / "trace.jsonl"
    trace.write_jsonl(path)

    table = render_table(
        ScheduleTrace.load_jsonl(path),
        source=path,
        first=1,
        last=2,
        title=r"\textsc{Ouro: refill} ($K{=}1$)",
    )

    lines = table.splitlines()
    assert lines[3] == r"  \multicolumn{7}{c}{\textsc{Ouro: refill} ($K{=}1$)} \\"
    assert lines[4] == r"   & Stage & $B$ & Detail & $Q_R$ & $Q_C$ & $Q_P$ \\"
    assert lines[5] == r"  \midrule"


@pytest.mark.parametrize("events", [[], _trace().events])
def test_render_table_rejects_incomplete_windows(tmp_path: Path, events: list[TraceEvent]) -> None:
    with pytest.raises(ValueError, match="requested launch window 1:20 is incomplete"):
        render_table(events, source=tmp_path / "trace.jsonl", first=1, last=20)


def test_render_table_rejects_missing_launch_inside_window(tmp_path: Path) -> None:
    events = _trace().events
    with pytest.raises(ValueError, match="requested launch window 1:2 is incomplete"):
        render_table([events[0], events[2]], source=tmp_path / "trace.jsonl", first=1, last=2)


def test_default_window_rejects_a_short_trace_without_writing_output(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    trace_path = tmp_path / "trace.jsonl"
    output = tmp_path / "table.tex"
    _trace().write_jsonl(trace_path)
    monkeypatch.setattr(sys, "argv", ["export_schedule_trace.py", str(trace_path), "--output", str(output)])

    with pytest.raises(ValueError, match="requested launch window 1:20 is incomplete"):
        main()
    assert not output.exists()


def test_a_run_that_never_queues_depth_work_shows_its_wave_decode_queue(tmp_path: Path) -> None:
    wave = ScheduleTrace()
    wave.tick = 4
    wave.record("prefill", 4, QueueSnapshot(1, 0, 0, 4, 0, 4), tokens=9)
    wave.record("prelude", 3, QueueSnapshot(1, 0, 0, 1, 0, 4), site="wave_cohort")
    wave.record("recurrent", 3, QueueSnapshot(1, 0, 0, 1, 0, 4), depths={0: 3}, exited=2)
    path = tmp_path / "wave.jsonl"
    wave.write_jsonl(path)

    table = render_table(ScheduleTrace.load_jsonl(path), source=path, first=1, last=3)

    lines = table.splitlines()
    assert lines[1] == r"\begin{tabular}{rlr>{\raggedright\arraybackslash}p{84pt}rr}"
    assert "$Q_R$" not in table and "$Q_C$" not in table
    rows = [line for line in lines if line.strip().endswith(r"\\") and not line.strip().startswith("&")]
    assert rows == [
        r"  0 & init &  &  & 0 & 5 \\",
        r"  1 & prefill & 4 & 9 prompt tokens & 4 & 1 \\",
        r"  2 & prelude & 3 &  & 1 & 1 \\",
        r"  3 & loop & \tracebatch{3} & $\mathrm{r}_{1}{:}3$; 2 exits & 1 & 1 \\",
    ]


def test_coda_threshold_must_be_positive(tmp_path: Path) -> None:
    with pytest.raises(ValueError, match="positive"):
        render_table(_trace().events, source=tmp_path / "trace.jsonl", first=1, last=4, coda_threshold=0)


def test_the_opening_state_holds_every_prompt_and_needs_a_trace_that_starts_at_prefill() -> None:
    events = _trace().events
    assert initial_queues(events) == QueueSnapshot(waiting=3, recurrent=0, coda=0, decode=0, coda_in_flight=0, active=0)
    with pytest.raises(ValueError, match="prefill"):
        initial_queues(events[1:])


def test_launch_window_must_be_an_ordered_one_based_range() -> None:
    assert parse_launch_window("1:40") == (1, 40)
    with pytest.raises(ValueError):
        parse_launch_window("5:2")
    with pytest.raises(ValueError):
        parse_launch_window("0:3")


def test_steady_state_window_opens_at_the_first_steady_launch() -> None:
    trace = ScheduleTrace()
    for tick, steady_flags in enumerate([(False, False), (False, True), (True, True)], start=1):
        trace.tick = tick
        for steady in steady_flags:
            trace.record("recurrent", 4, QueueSnapshot(0, 0, 0, 4, 0, 4), steady=steady, depths={0: 4})

    assert steady_state_window(trace.events, length=3) == (4, 6)
    assert steady_state_window(trace.events, length=1) == (4, 4)


def test_steady_state_window_rejects_a_run_without_one_and_a_non_positive_length() -> None:
    trace = ScheduleTrace()
    trace.record("coda", 1, QueueSnapshot(0, 0, 0, 1, 0, 1), steady=True)
    with pytest.raises(ValueError, match="steady-state window"):
        steady_state_window([], length=4)
    with pytest.raises(ValueError, match="length"):
        steady_state_window(trace.events, length=0)
